### ISSUE TITLE
pagination的標籤使用

### ISSUE THREAD

**Issue by nissenyeh** [pvt5r486/CrossGate#1]
你好，我也是六角的同學，來參考你的作業答案
我想請問：
在components/pages/products.vue 這個程式碼中< pagination >這個標籤，明明沒有import近來

```
像是：
import pagination from "../pagination"
```
為什麼可以用呢？>.<

**Comment by pvt5r486** [comment]
@NissanYeah 
抱歉現在才看到，很可能你已經自行解決問題了...

因為我在main.js內寫了
import pagination from '@/components/pagination';
Vue.component('pagination',pagination);
這麼做可以讓我全域的使用我寫的<pagination>

希望能幫助到你:D
我也還在努力最終作業呢
