### ISSUE TITLE
CG的圖片資源

### ISSUE THREAD

**Issue by LZ9** [pvt5r486/CrossGate#2]
你好，我也非常喜歡CG這款遊戲，我這幾天也一直在找CG相關的人物頭像的圖片以及寵物的圖鑒圖片，我想要完成一個CG相關的Android的APP，不知道你這邊是否有資源可以共享幫助我，非常感謝~~

**Comment by pvt5r486** [comment]
@LZ9  這部分的資料其實我也蠻少的，就如同我在網頁中介紹的那樣。所以很可能幫不上忙，不過如果你想要這部分的資訊，可以給你個關鍵字「水藍魔力」，雖然在這邊宣傳這個不太好啦，不過搭配一下美工技術應該就能獲得不錯的素材了。

不過這個網站有它自己的討論區、攻略站、還有很多能用的東西，希望能幫到你！
當然也可以直接註冊進入遊戲直接在遊戲內截圖~

**Comment by LZ9** [comment]
@pvt5r486 感謝你提供的資源，對我非常有幫助，非常感謝~
